# window.py
#
# Copyright 2024 mirkobrombin
# Copyright 2024 muqtadir
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundationat version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import logging
import os
from gettext import gettext as _

from gi.repository import Adw, GLib, Gtk

from tuna_installer.utils.builder import Builder
from tuna_installer.utils.processor import Processor
from tuna_installer.views.confirm import VanillaConfirm
from tuna_installer.views.done import VanillaDone
from tuna_installer.views.progress import VanillaProgress

logger = logging.getLogger("Installer::Window")


@Gtk.Template(resource_path="/org/tunaos/Installer/gtk/window.ui")
class VanillaWindow(Adw.ApplicationWindow):
    __gtype_name__ = "VanillaWindow"

    carousel = Gtk.Template.Child()
    carousel_indicator_dots = Gtk.Template.Child()
    btn_back = Gtk.Template.Child()
    btn_next = Gtk.Template.Child()
    btn_exit = Gtk.Template.Child()
    toasts = Gtk.Template.Child()

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # this starts the builder and generates the widgets
        # to put in the carousel
        self.__builder = Builder(self)

        # system views
        self.__view_confirm = VanillaConfirm(self)
        self.__view_progress = VanillaProgress(self, self.recipe.get("tour", {}))
        self.__view_done = VanillaDone(self)

        # sensitivity-tracking state for the header btn_next
        self.__next_page_widget = None
        self.__next_handlers = []

        # this builds the UI with the widgets generated by the builder
        self.__build_ui()

        # connect system signals
        self.__connect_signals()

        # some variables to track state
        self.install_mode = 0

    def __connect_signals(self):
        self.btn_back.connect("clicked", self.back)
        self.btn_next.connect("clicked", self.__on_header_next)
        self.btn_exit.connect("clicked", self.__on_exit_clicked)
        self.carousel.connect("page-changed", self.__on_page_changed)
        # Connect update_finals to whichever step widget was last added to the
        # carousel — this may differ from widgets[-1] when a screen is skipped.
        if self.__last_step_widget is not None:
            self.__last_step_widget.btn_next.connect("clicked", self.update_finals)
        else:
            self.__builder.widgets[-1].btn_next.connect("clicked", self.update_finals)
        self.__view_confirm.connect("installation-confirmed", self.on_installation_confirmed)

        if os.environ.get("TUNA_TEST"):
            self.carousel.connect("page-changed", self.__on_page_changed_test)
            # Welcome is the first page — no page-changed fires for it, kick it manually
            GLib.timeout_add(600, self.__test_advance_first_page)

    def __test_advance_first_page(self):
        page = self.carousel.get_nth_page(0)
        if hasattr(page, "test_auto_advance"):
            page.test_auto_advance()
        return GLib.SOURCE_REMOVE

    def __on_page_changed_test(self, carousel, index):
        page = carousel.get_nth_page(int(index))
        if hasattr(page, "test_auto_advance"):
            # 700ms: enough for animations + update_finals() to have run
            GLib.timeout_add(700, lambda: page.test_auto_advance() or GLib.SOURCE_REMOVE)

    def rebuild_ui(self, mode=1):
        self.install_mode = mode
        self.__build_ui(True, mode)

    def __build_ui(self, rebuild=False, mode=0):
        property_list = self.__builder.property_list

        if rebuild:
            self.carousel.remove(self.__view_confirm)
            self.carousel.remove(self.__view_progress)
            self.carousel.remove(self.__view_done)

        self.__last_step_widget = None

        if "VANILLA_FORCE_TOUR" not in os.environ:
            for i, widget in enumerate(self.__builder.widgets):
                if rebuild:
                    if "protected" in property_list[i]:
                        continue
                    else:
                        self.carousel.remove(widget)
                if "custom_image" in property_list[i] and mode == 0:
                    continue
                if "default_image" in property_list[i] and mode == 1:
                    continue
                if getattr(widget, "skip_screen", False):
                    logger.info("(%s) Skipping single-image screen", widget.__gtype_name__)
                    continue
                logger.info("(%s) Adding widget to carousel", widget.__gtype_name__)
                self.carousel.append(widget)
                self.__last_step_widget = widget
        else:
            self.__on_page_changed()

        self.carousel.append(self.__view_confirm)
        self.carousel.append(self.__view_progress)
        self.carousel.append(self.__view_done)

    def __on_page_changed(self, *args):
        cur_index = self.carousel.get_position()
        page = self.carousel.get_nth_page(cur_index)

        logger.info("(%s) Page is changing...", page.__gtype_name__)

        # Disconnect sensitivity tracking from previous page
        if self.__next_page_widget is not None:
            for h in self.__next_handlers:
                try:
                    self.__next_page_widget.btn_next.disconnect(h)
                except Exception:
                    pass
            self.__next_page_widget = None
            self.__next_handlers = []

        is_final = page in [self.__view_progress, self.__view_done]
        is_confirm = page == self.__view_confirm

        if is_final or is_confirm:
            logger.info("(%s) It is a final page", page.__gtype_name__)
            self.btn_back.set_visible(False)
            self.btn_back.set_sensitive(False)
            self.carousel_indicator_dots.set_visible(False)
            self.btn_next.set_visible(False)
            return

        logger.info("(%s) It is not a final page", page.__gtype_name__)
        self.btn_back.set_visible(cur_index != 0.0)
        self.btn_back.set_sensitive(cur_index != 0.0)
        self.carousel_indicator_dots.set_visible(cur_index != 0.0)

        # Sync header btn_next with the current page's btn_next
        if hasattr(page, "btn_next"):
            self.btn_next.set_visible(page.btn_next.get_visible())
            self.btn_next.set_sensitive(page.btn_next.get_sensitive())

            def _sync(widget, _param):
                self.btn_next.set_visible(widget.get_visible())
                self.btn_next.set_sensitive(widget.get_sensitive())

            self.__next_handlers = [
                page.btn_next.connect("notify::sensitive", _sync),
                page.btn_next.connect("notify::visible", _sync),
            ]
            self.__next_page_widget = page
        else:
            self.btn_next.set_visible(False)

    def __on_header_next(self, *args):
        cur_index = int(self.carousel.get_position())
        page = self.carousel.get_nth_page(cur_index)
        if hasattr(page, "btn_next"):
            page.btn_next.emit("clicked")

    def __on_exit_clicked(self, *args):
        dialog = Adw.AlertDialog(
            heading=_("Exit Installer?"),
            body=_("Any progress will be lost."),
        )
        dialog.add_response("cancel", _("Cancel"))
        dialog.add_response("exit", _("Exit"))
        dialog.set_response_appearance("exit", Adw.ResponseAppearance.DESTRUCTIVE)
        dialog.set_default_response("cancel")
        dialog.set_close_response("cancel")
        dialog.connect("response", self.__on_exit_response)
        dialog.present(self)

    def __on_exit_response(self, dialog, response):
        if response == "exit":
            self.get_application().quit()

    def update_finals(self, *args):
        # collect all the finals
        if "VANILLA_FORCE_TOUR" not in os.environ:
            self.finals = self.__builder.get_finals()
        else:
            self.finals = json.loads(os.environ["VANILLA_FORCE_TOUR"])

        # extract the pretty name from whichever image finals key is present
        self.pretty_name = None
        for f in self.finals:
            if isinstance(f, dict) and "pretty_name" in f:
                self.pretty_name = f["pretty_name"]
                break

        self.__view_confirm.update(self.finals)

    def on_installation_confirmed(self, *args):
        recipe = Processor.gen_install_recipe(
            self.recipe.get("log_file", "/tmp/vanilla_installer.log"),
            self.finals,
            self.recipe,
        )
        self.next()
        self.__view_progress.start(recipe)

    def next(self, widget=None, fn=None, *args):
        logger.info("Going to next page")

        cur_index = self.carousel.get_position()
        if int(cur_index) >= self.carousel.get_n_pages() - 1:
            logger.info(f"Already on last page ({int(cur_index)}), ignoring next()")
            return
        page = self.carousel.get_nth_page(cur_index)
        if page.delta:
            logger.info(f"Removing deltas of page {int(cur_index)}")
            page.del_deltas()
        logger.info(f"Next page is {int(cur_index + 1)}")

        if fn is not None:
            logger.info("Executing page's custom function")
            fn()
            logger.info("Finished executing page's custom function")

        page = self.carousel.get_nth_page(cur_index + 1)
        self.carousel.scroll_to(page, True)
        if page.delta:
            logger.info(f"Generating deltas of page {int(cur_index + 1)}")
            page.gen_deltas()

    def back(self, *args):
        logger.info("Going to previous page")

        cur_index = self.carousel.get_position()
        page = self.carousel.get_nth_page(cur_index)
        if page.delta:
            page.del_deltas()
        logger.info(f"Previous page is {int(cur_index - 1)}")

        page = self.carousel.get_nth_page(cur_index - 1)
        self.carousel.scroll_to(page, True)
        if page.delta:
            page.gen_deltas()

    def toast(self, message, timeout=3):
        toast = Adw.Toast.new(message)
        toast.props.timeout = timeout
        self.toasts.add_toast(toast)

    def set_installation_result(self, result, terminal):
        if result:
            logger.info("Installation complete!")
        else:
            logger.error("Installation failed!")
        self.__view_done.set_result(result, terminal)
        self.next()
